### ISSUE TITLE
Check for ports already in use

### ISSUE THREAD

**Issue by sujen1412** [memex-explorer/sce#1]
@giuseppetotaro 
For the docker-compose up to work correctly, we need to check if the following ports are available 
1. 8983
2. 5000
3. 9559 and
4. 4444

If these ports are not available we should ask the user to make them available while running the kickstart.sh script ?

**Comment by giuseppetotaro** [comment]
Closed by commit number 3b984b9412818fdcbbc06b7f365260f95315b88c
The actual port numbers are reported to the user. When [kickstart.sh](https://github.com/memex-explorer/sce/blob/master/kickstart.sh) has completed, it writes out how to reach the services through the following lines:
`echo "The Solr instance is available on http://0.0.0.0:${SOLR_PORT}"`
`echo "The DD explorer is available on http://0.0.0.0:${DD_PORT}"`
