### ISSUE TITLE
Enable deep crawling using Sparker 

### ISSUE THREAD

**Issue by sujen1412** [memex-explorer/sce#13]
To enable deep crawling we would need two sparkler deployments configured in a way to enable deep crawling. 
This would mean we would change the way we are deploying our system. 
Instead of running an embedded solr within the sparkelr container we would separate it out in its own container. 
We would then have 5 containers running 
1 SOLR, 2 Sparklers, 1 DD Tool, 1 Firefox.

**Comment by wmburke** [comment]
This is not what we did. Instead, we run deep crawls alternately with broad crawls in the same Sparkler container. First round is deep, second round is broad, etc...

@sujen1412, please amend if I'm missing anything relevant.
