### ISSUE TITLE
Add uninstall instructions to the User Guide

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/sce#15]

**Comment by sujen1412** [comment]
1. First stop all running containers
`./kickstart.sh -down`

2. Check if any containers are running or not
`docker ps`
You should not see any running containers. If you see any container running then run this
`docker stop $(docker ps -aq)`

3. Now delete all images on your machine
`docker rmi -f $(docker images -aq)`

Check if any images are on your machine
`docker images`
This should show you 0 images.

4. After the above, you can go ahead and delete the sce directory 
`sudo rm -rf sce`
CAUTION: THIS WILL ALSO DELETE ALL YOUR CRAWL DATA

To avoid deleting all your crawl data, do not delete the sce directory. To re-install without deleting the sce directory just run the following after step 3 from the sce directory
`git pull --all`
`./kickstart.sh`
