### ISSUE TITLE
sce.sh functionality

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/sce#2]
The default functionality for sce.sh should be the following:
1. if -i (number of iterations) is not specified, run until stopped
2. if -l (log) is not specified, it should automatically create a log while also outputting to screen
3. if -id (job id) is not specified, it should automatically create one based on the seed-list name and a timestamp (or whatever makes sense)

**Comment by giuseppetotaro** [comment]
@wmburke The commit number afc85105a852faf53c9571b8f04c50073a14fd4e provides to [sce.sh](https://github.com/memex-explorer/sce/blob/master/sce.sh) the ability to create a default log file as reported in my comment on #4.
The job identifier is by default set to the basename of the seed file unless the user gives it by using the `-id` option (it allows the user to specify a meaningful job name).
We will close the issue once we figure out the best way to perform an "unlimited" number of iterations and exit gracefully if the user wants to stop the job.

**Comment by giuseppetotaro** [comment]
Closed by commit c8fc460b27d595d7492bb6b94e8f16c5c685e0e7 so that the crawl job runs until the user hits CTRL-C.
