### ISSUE TITLE
kickstart.sh -l default

### ISSUE THREAD

**Issue by wmburke** [memex-explorer/sce#4]
if -l (log) is not specified, it should automatically create a log while also outputting to screen

**Comment by giuseppetotaro** [comment]
Closed by commit number 3b984b9412818fdcbbc06b7f365260f95315b88c inspired by Nutch.
If the user does not give any log pathname, [kickstart.sh](https://github.com/memex-explorer/sce/blob/master/kickstart.sh) checks if a kickstart.log file exists, if yes dumps it using the timestamp as suffix, and then creates a new kickstart.log file in the logs directory.
