### ISSUE TITLE
Allow for infinite crawling 

### ISSUE THREAD

**Issue by sujen1412** [memex-explorer/sce#5]
Make provisions in the sce.sh script to let a crawl run till a user presses CRTL+C

**Comment by sujen1412** [comment]
@wmburke @giuseppetotaro, by default we plan to provide crawling in batches of 10 iterations at a time (with 12 groups in one iteration) before the script would detect a CTRL+C. 

This means that if a user presses CTRL+C while iteration 1 is going on, the script would complete all remaining and safely exit, not killing any crawls mid way. But this may mean the user would have to wait for longer. To reduce wait times we could decrease the number for 10 to something smaller. 
Note : reducing to something smaller incurs an overhead of starting sparkler everytime (reserving JVM resources and spark, etc)

**Comment by wmburke** [comment]
When Ctrl+C is hit, can we show them a message? eg, "It may take up to 30 minutes to stop gracefully. If you want to force a stop (and potentially lose some of the collected data), press Ctrl+C again."

Wayne Moses Burke, MS
Cognizant Engineer
Instrument Software and Science Data Systems Section (398)
NASA Jet Propulsion Laboratory Pasadena, CA 91109 USA
Mailstop: 168-527
E-mail: Wayne.M.Burke@jpl.nasa.gov<mailto:Wayne.M.Burke@jpl.nasa.gov>

On 06/15/2017 01:37 PM, Sujen Shah wrote:

@wmburke<https://github.com/wmburke> @giuseppetotaro<https://github.com/giuseppetotaro>, by default we plan to provide crawling in batches of 10 iterations at a time (with 12 groups in one iteration) before the script would detect a CTRL+C.

This means that if a user presses CTRL+C while iteration 1 is going on, the script would complete all remaining and safely exit, not killing any crawls mid way. But this may mean the user would have to wait for longer. To reduce wait times we could decrease the number for 10 to something smaller.
Note : reducing to something smaller incurs an overhead of start sparkler everytime (reserving JVM resources and spark, etc)

**Comment by giuseppetotaro** [comment]
Closed by commit c8fc460b27d595d7492bb6b94e8f16c5c685e0e7 so that when CRTL-C is hit the user can force to stop the crawl job instead of waiting the job ends gracefully.
Furthermore, the user can now use the `kill` sub-command (e.g., `./sce.sh kill`) to force the stop of a running crawl job (commit 61b0141b6f6458043a74c1d6e57143a0bedddba7).
