### ISSUE TITLE
Use bash tee command to redirect output to log file and console 

### ISSUE THREAD

**Issue by sujen1412** [memex-explorer/sce#6]
Doing the above will be better as the user can see the progress rather than just seeing a black screen for 30mins while the install in underway.

**Comment by giuseppetotaro** [comment]
Closed by commits f095f0278f7e904d29eb5fea3899c7a1aa38c02a and c8fc460b27d595d7492bb6b94e8f16c5c685e0e7. All the log messages for both [kickstart.sh](https://github.com/memex-explorer/sce/blob/master/kickstart.sh) and [sce.sh](https://github.com/memex-explorer/sce/blob/master/sce.sh) are now reported to console and the log file through the [tee](https://en.wikipedia.org/wiki/Tee_(command)) command.
